### ISSUE TITLE
quoteRead

### ISSUE THREAD

**Issue by aslepakurov** [aslepakurov/almost_java#3]
Make it regexp. push to parse method, add return Token (TokenType.TK_STRING) part

**Comment by gribozavr** [comment]
No regexps, please.

**Comment by ghost** [comment]
why no regexps? i thought it's simpler for reading and understanding

**Comment by gribozavr** [comment]
I totally agree that using a regexp might be simpler.  But there are a few cons:
- the point of the class is learning to write lexers and parsers, thus we should do the parsing by hand (there are lots of parser generators that could generate the whole parser from the grammar automatically);
- it will be easier to understand for someone who is not familiar with Java regex APIs.
